from __future__ import annotations

from typing import Protocol

from tradenum.domain.models import Ticket


class LedgerPort(Protocol):
    def next_id(self) -> str: ...
    def save(self, ticket: Ticket) -> Ticket: ...
    def get(self, ticket_id: str) -> Ticket | None: ...
    def all(self) -> list[Ticket]: ...
    def open(self) -> list[Ticket]: ...
    def stats(self) -> dict: ...
